# Generated by Django 3.1 on 2020-12-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50, null=True)),
                ('auth_flag', models.CharField(max_length=50, null=True)),
                ('req_url', models.CharField(max_length=250, null=True)),
                ('content', models.CharField(max_length=300, null=True)),
                ('component', models.CharField(max_length=50, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.auths')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolesToAuthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authosKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.auths')),
                ('rolesKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.roles')),
            ],
        ),
    ]
