# Generated by Django 3.1 on 2020-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_member_roleskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='info_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
