# Generated by Django 3.1 on 2020-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_member_info_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=50, null=True)),
                ('c2', models.CharField(max_length=50, null=True)),
                ('c3', models.CharField(max_length=50, null=True)),
                ('c4', models.CharField(max_length=50, null=True)),
                ('c5', models.CharField(max_length=50, null=True)),
                ('c6', models.CharField(max_length=50, null=True)),
                ('c7', models.CharField(max_length=50, null=True)),
                ('c8', models.CharField(max_length=50, null=True)),
                ('c9', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
