# Generated by Django 3.1 on 2020-12-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_demodata_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excuterecord',
            name='startDateTime',
        ),
        migrations.AlterField(
            model_name='excuterecord',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='excuterecord',
            name='endDateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
